"""Generate the committed gripper-port assets from the vendored robosuite tree.

Two outputs, both written with a "generated by" header and meant to be committed:

  assets/grippers/<name>.xml   robosuite gripper MJCFs patched for Genesis:
                               repo-relative meshdir/texturedir, no `group` attr
                               on <default>, deduped <mesh> names, identity base
                               body (Genesis keeps a phantom `world` link behind
                               a non-identity base, which breaks
                               RigidEntity.attach — the removed transform is
                               reported and belongs in the GripperModel
                               mount_pos/mount_quat fields), and no
                               <equality><tendon> couplings (unsupported).
  assets/xarm7_nogripper.urdf  the arm alone: gripper subtree, joint_tcp and
                               link_tcp dropped, chain ends at link_eef.

    uv run python scripts/port_grippers.py
"""

from __future__ import annotations

import xml.etree.ElementTree as ET
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
RS_GRIPPERS = REPO / "robosuite/robosuite/models/assets/grippers"
OUT_GRIPPERS = REPO / "assets/grippers"
URDF_IN = REPO / "xarm7_standalone.urdf"
URDF_OUT = REPO / "assets/xarm7_nogripper.urdf"
HEADER = "generated by scripts/port_grippers.py — do not edit by hand"

XMLS = [
    "rethink_gripper.xml",
    "panda_gripper.xml",
    "bd_gripper.xml",
    "robotiq_gripper_85.xml",
    "robotiq_gripper_140.xml",
    "jaco_three_finger_gripper.xml",
    "robotiq_gripper_s.xml",
    "xarm7_gripper.xml",  # not used by a robot variant; mount-frame check only
]


def patch_gripper(src: Path, dst: Path) -> list[str]:
    """Patch one robosuite gripper MJCF for Genesis; returns the applied fixes."""
    fixes = []
    tree = ET.parse(src)
    root = tree.getroot()

    compiler = root.find("compiler")
    if compiler is None:
        compiler = ET.SubElement(root, "compiler")
    rel = Path(*[".."] * len(dst.parent.relative_to(REPO).parts)) / (
        src.parent.relative_to(REPO)
    )
    compiler.set("meshdir", str(rel))
    compiler.set("texturedir", str(rel))
    # robosuite merges gripper XMLs into a robot model whose compiler sets
    # radians; standalone the mujoco default is DEGREES, which shrinks every
    # hinge range/ctrlrange ~57x (robotiq "0 0.8" became 0..0.014 rad)
    compiler.set("angle", "radian")

    for d in root.iter("default"):  # invalid attribute; mujoco's schema rejects it
        if "group" in d.attrib:
            del d.attrib["group"]
            fixes.append("dropped group= on <default>")

    seen = set()  # duplicate mesh names: keep the first definition
    for asset in root.iter("asset"):
        for mesh in asset.findall("mesh"):
            if mesh.get("name") in seen:
                asset.remove(mesh)
                fixes.append(f"dropped duplicate mesh {mesh.get('name')}")
            else:
                seen.add(mesh.get("name"))

    # identity base body: the removed transform goes in GripperModel.mount_*
    for body in root.find("worldbody").findall("body"):
        pos, quat = body.get("pos", "0 0 0"), body.get("quat", "1 0 0 0")
        if [float(x) for x in pos.split()] != [0, 0, 0] or [
            float(x) for x in quat.split()
        ] != [1, 0, 0, 0]:
            body.set("pos", "0 0 0")
            body.set("quat", "1 0 0 0")
            fixes.append(f"zeroed base transform: mount_pos={pos} mount_quat={quat}")

    for eq in root.iter("equality"):  # genesis: connect/weld/joint equalities only
        for t in eq.findall("tendon"):
            eq.remove(t)
            fixes.append(f"stripped equality/tendon {t.get('name')}")

    root.insert(0, ET.Comment(f" {HEADER} "))
    tree.write(dst)
    return fixes


def strip_gripper_urdf(src: Path, dst: Path) -> tuple[list[str], list[str]]:
    """Drop the gripper subtree (and joint_tcp/link_tcp) from the xArm7 URDF."""
    tree = ET.parse(src)
    root = tree.getroot()
    joints = root.findall("joint")

    # collect the subtree hanging below link_eef (gripper base, fingers, tcp)
    drop_links: set[str] = set()
    frontier = {"link_eef"}
    while frontier:
        parent = frontier.pop()
        for j in joints:
            if j.find("parent").get("link") == parent:
                child = j.find("child").get("link")
                drop_links.add(child)
                frontier.add(child)

    drop_joints = {
        j.get("name")
        for j in joints
        if j.find("parent").get("link") in drop_links
        or j.find("child").get("link") in drop_links
    }
    for el in list(root):
        if el.tag == "link" and el.get("name") in drop_links:
            root.remove(el)
        elif el.tag == "joint" and el.get("name") in drop_joints:
            root.remove(el)
        elif el.tag == "transmission":
            j = el.find("joint")
            if j is not None and j.get("name") in drop_joints:
                root.remove(el)
        elif el.tag == "gazebo" and el.get("reference") in drop_links | drop_joints:
            root.remove(el)

    # the source URDF sits at the repo root and references assets/<mesh>.stl;
    # this file lives IN assets/, so the prefix comes off
    for mesh in root.iter("mesh"):
        fn = mesh.get("filename", "")
        if fn.startswith("assets/"):
            mesh.set("filename", fn[len("assets/") :])

    root.insert(0, ET.Comment(f" {HEADER} "))
    tree.write(dst)
    return sorted(drop_links), sorted(drop_joints)


if __name__ == "__main__":
    OUT_GRIPPERS.mkdir(parents=True, exist_ok=True)
    for name in XMLS:
        fixes = patch_gripper(RS_GRIPPERS / name, OUT_GRIPPERS / name)
        print(f"[{name}]")
        for f in fixes:
            print(f"  {f}")
    links, joints = strip_gripper_urdf(URDF_IN, URDF_OUT)
    print(f"[{URDF_OUT.name}] dropped links: {links}")
    print(f"[{URDF_OUT.name}] dropped joints: {joints}")
