"""Generate the committed RUKA v2 assets from the xclients merged URDFs.

Copies xclients/urdf/generated/xarm7_ruka_{right,left}.urdf (the non-coarse
variants — the _coarse ones carry a 15.5 cm collision proxy sphere) plus every
referenced STL into assets/ruka/, rewriting the absolute mesh filename
attributes to be relative to the URDF's own directory. Both URDFs reference
the same mesh set (the left mirrors via scale="-1 1 1"), so the copy is flat.

    uv run python scripts/port_ruka.py
"""

from __future__ import annotations

import shutil
import xml.etree.ElementTree as ET
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SRC = Path("/home/mhyatt000/repo/xclients/urdf/generated")
OUT = REPO / "assets/ruka"
HEADER = "generated by scripts/port_ruka.py — do not edit by hand"

URDFS = ["xarm7_ruka_right.urdf", "xarm7_ruka_left.urdf"]


def port(src: Path, dst: Path) -> list[Path]:
    """Copy one URDF with basename-relative mesh paths; returns the meshes."""
    tree = ET.parse(src)
    root = tree.getroot()
    meshes = []
    for mesh in root.iter("mesh"):
        fn = Path(mesh.get("filename"))
        meshes.append(fn)
        mesh.set("filename", fn.name)
    root.insert(0, ET.Comment(f" {HEADER} "))
    tree.write(dst)
    return meshes


if __name__ == "__main__":
    OUT.mkdir(parents=True, exist_ok=True)
    copied: set[str] = set()
    for name in URDFS:
        for fn in port(SRC / name, OUT / name):
            if fn.name not in copied:
                shutil.copy(fn, OUT / fn.name)
                copied.add(fn.name)
        print(f"[{name}] rewritten, {len(copied)} meshes total")
    print(f"copied {len(copied)} STLs to {OUT}")
